name: The Wit
favicon: null
layout_spectrum: 0.40332
typography_spectrum: 0.18676149402745068
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0
  lightness: 0.3125
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
