name: The Wit
favicon: null
layout_spectrum: 0.25224
typography_spectrum: 0.33572
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#3500c9'
    - '#c0c0c0'
    - '#4f4f4f'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
